### ISSUE TITLE
"Ejson is not supported on your platform" error

### ISSUE THREAD

**Issue by jacobbridges** [Shopify/ejson#24]
I have installed Ejson on KDE5 (using `gem install ejson`), and when I type "ejson" an infinite stream of the error "Ejson is not supported on your platform" is printed. 

So, for visual explanation:

```
$ sudo gem install ejson 
Fetching: ejson-1.0.1.gem (100%)
Successfully installed ejson-1.0.1
Parsing documentation for ejson-1.0.1
Installing ri documentation for ejson-1.0.1
Done installing documentation for ejson after 0 seconds
1 gem installed

$ ejson
Ejson is not supported on your platform.
Ejson is not supported on your platform.
Ejson is not supported on your platform.
Ejson is not supported on your platform.
Ejson is not supported on your platform.
Ejson is not supported on your platform.
^C/usr/lib/ruby/2.1.0/rubygems.rb:8:in `require': Interrupt
        from /usr/lib/ruby/2.1.0/rubygems.rb:8:in `<top (required)>'
        from <internal:gem_prelude>:1:in `require'
        from <internal:gem_prelude>:1:in `<compiled>'

```

**Comment by burke** [comment]
Maybe you're on a 32-bit linux? What does `uname -sm` say?

**Comment by burke** [comment]
I just pushed f8d6b2736098baf949851cc9a7238109cd6b4323 which improves the failure mode a little better.

**Comment by jacobbridges** [comment]
Oh yes I"m definitely on 32-bit Linux. 

```
$ uname -i
i686
```

I just wanted to report the infinite error. :) Thanks for the awesome project! Wish there was a 32 bit version available... :(
